In [4]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D
from tensorflow.keras.layers import Activation, Dropout, Flatten, Dense
from tensorflow.keras import backend as K
import tensorflow as tf

# dimensions of our images.
img_width, img_height = 150, 150
train_data_dir = 'data/train'
validation_data_dir = 'data/validation'
epochs = 50
batch_size = 16

if K.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)
def build_model():
    model = tf.keras.models.Sequential()
    model.add(tf.keras.layers.Conv2D(64, (3, 3), input_shape=input_shape))
    model.add(tf.keras.layers.Activation('relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

    model.add(tf.keras.layers.Conv2D(64, (3, 3)))
    model.add(tf.keras.layers.Activation('relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))
    
    model.add(tf.keras.layers.Conv2D(64, (3, 3)))
    model.add(tf.keras.layers.Activation('relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

    model.add(tf.keras.layers.Conv2D(128, (3, 3)))
    model.add(tf.keras.layers.Activation('relu'))
    model.add(tf.keras.layers.MaxPooling2D(pool_size=(2, 2)))

    model.add(tf.keras.layers.Flatten())
    model.add(tf.keras.layers.Dense(128))
    model.add(tf.keras.layers.Activation('relu'))
    model.add(tf.keras.layers.Dropout(0.5))
    model.add(tf.keras.layers.Dense(3,activation='softmax'))

    model.compile(loss='categorical_crossentropy',
          optimizer='rmsprop',
          metrics=['accuracy'])
    return model

model = build_model()
train_datagen = ImageDataGenerator(
    rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)


test_datagen = ImageDataGenerator(rescale=1. / 255,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True)

train_generator = train_datagen.flow_from_directory(
    train_data_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size)

validation_generator = test_datagen.flow_from_directory(
    validation_data_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size)

Found 659 images belonging to 3 classes.
Found 79 images belonging to 3 classes.


In [ ]:
nb_train_samples = 659
nb_validation_samples = 79
model.fit_generator(
    train_generator,
    steps_per_epoch=nb_train_samples // batch_size,
    epochs=epochs,
    validation_data=validation_generator,
    validation_steps=nb_validation_samples // batch_size)

model.save_weights('second_try.h5')

Epoch 1/50
41/41 [==============================] - 70s 2s/step - loss: 1.2618 - acc: 0.3771 - val_loss: 1.1021 - val_acc: 0.2969
Epoch 2/50
41/41 [==============================] - 67s 2s/step - loss: 1.0920 - acc: 0.4399 - val_loss: 1.1831 - val_acc: 0.2812
Epoch 3/50
41/41 [==============================] - 67s 2s/step - loss: 1.0145 - acc: 0.5570 - val_loss: 1.1758 - val_acc: 0.4531
Epoch 4/50
41/41 [==============================] - 68s 2s/step - loss: 0.8858 - acc: 0.6220 - val_loss: 1.1171 - val_acc: 0.4219
Epoch 5/50
11/41 [=======>......................] - ETA: 41s - loss: 0.8912 - acc: 0.6572

In [1]:
import cv2

In [23]:
img = cv2.imread('/Users/anirudhmuhnot/Desktop/OneDrive - technonjr.org/github/damage_analyser/Data/train/broken_windshield/00000052.jpg')
img = cv2.resize(img,(200,200))
img = img.reshape([1,200,200,3])

In [18]:
###########################################################################################
from tensorflow import keras
import tensorflow as tf

In [19]:
img_width, img_height =200, 200
if tf.keras.backend.image_data_format() == 'channels_first':
    input_shape = (3, img_width, img_height)
else:
    input_shape = (img_width, img_height, 3)

In [21]:
model = tf.keras.applications.Xception(include_top=True, weights=None, input_tensor=None, input_shape=input_shape,
                                           pooling='max', classes=5)
model.compile(loss='categorical_crossentropy',
                  optimizer='rmsprop',
                  metrics=['accuracy'])
model.load_weights('a.h5')

In [24]:
pred = model.predict(img)
print(pred)

[[0. 0. 0. 1. 0.]]


In [33]:
print(model1.predict(img))
print(model.predict(img))

[[0. 0. 1. 0. 0.]]
[[0. 0. 1. 0. 0.]]


In [41]:
d_inv

{0: 'broken_bumper',
 1: 'broken_lights',
 2: 'broken_windshield',
 3: 'flat_tire',
 4: 'positives'}